apiVersion: apps/v1
kind: Deployment
metadata:
    name: jfrog-demo-deployment
spec:
    selector:
        matchLabels:
           app: jfrog-demo
    replicas: 2 # tells deployment to run 2 pods matching the template
    template:
      metadata:
          labels:
             app: jfrog-demo
      spec:
        containers:
        - name: frog-demo
          image: jfrog-demo:47
          ports:
          - containerPort: 80
